project:
  type: website
  output-dir: docs  # Set output directory for GitHub Pages

website:
  title: "Richard_Sen_Xiao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

